### PR TITLE
Solve pass problem, add C-style comments and type declarations

### PR DESCRIPTION
**Pull request by Willie169**
Close temporarily. I will need a good debugging before next PR.

Sorry, please wait a minute before approve it, I just found another bug in [parser.py](https://github.com/Willie169/bython/blob/pisDev/bython%2Fparser.py).

This project is one of my favorite projects. It is just so miraculous that I can write Python without noticing indentations. 

In this PR, I added features to convert C-style type declarations to Python type hint, translate comments from C-style to Python, and add pass statements where needed in empty code blocks. I didn't change bython standard format (like `py2by` output) though, cuz I think it's better to let bython remain Python-like, just with {} than indentation.

I changed the version number to 1.0 cuz I think there maybe someone who don't need these new features, the original v0.8 can be their option, which maybe with shorter parsing time cuz less overheat.

It might be better to add more args in `bython` and `by2py` to indicate whether accepting by_type, type declaration, etc. I am not good at writing that and I afraid I will mess the code up so I will not write this feature so far. Thanks in advance if someone can make this, or I might make this one day after I get more familiar with them.
 
Please review [parser.py](https://github.com/Willie169/bython/blob/pisDev/bython%2Fparser.py) if you have time. Thanks in advance for your assistance.

### CODE REVIEW

**Comment by Willie169** [comment]
Wait. Don't approve it yet. I found a bug.

**Comment by Willie169** [comment]
Code is kinda done.  I will write some testcases latter.

**Comment by Willie169** [comment]
I am gonna depreciate the c_type in my original code and change it to by_type, which is types specific to bython that starts with "by_" (e.g. "by_deque": "collections.deque"). Otherwise it will just remain the type name (e.g. int in int x = 1;). These enable quick conversion from type declaration to type hint.

**Comment by Willie169** [comment]
It might be better to add more args in `bython` and `by2py` to indicate whether accepting by_type, type declaration, etc. I am not good at writing that and I afraid I will mess the code up so I will not write this feature so far. Thanks in advance if someone can make this, or I might make this one day after I get more familiar with them.

**Comment by Willie169** [comment]
Sorry, another bug found.

**Comment by Willie169** [comment]
Close PR temporarily. I will make another request after a good debugging.

**Comment by ll-bit-demon** [comment]
six years after last commit, i dont think author will respond

**Comment by Willie169** [comment]
Yup. Maybe I will create a new repo and refactor everything with antlr4. I haven't decided which route to go, but release won't be too soon, at least after I pass the GSAT.

**Pull request closed without merging**
